export { default as Header } from './Header'
export { default as PostCard } from './PostCard'
export { default as Categories } from './Categories'
export { default as Layout } from './Layout'
export { default as Comments } from './Comments'
export { default as CommentsForm} from './CommentsForm'
export { default as AuthorDetail } from './AuthorDetail'
export { default as PostDetailPage } from './PostDetailPage'
export { default as RelatedPosts } from './RelatedPosts'